import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';
import './globals.css';
import MainLayout from '@/components/layout/MainLayout';
import QueryProvider from '@/providers/queryProvider';
import { AuthContextProvider } from '@/contexts/AuthContext';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cartify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <QueryProvider>
          <AuthContextProvider>
            <MainLayout>{children}</MainLayout>
          </AuthContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
