import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/providers/queryProvider';
import { AuthContextProvider } from '@/contexts/AuthContext';
import { WizardsContextProvider } from '@/contexts/WizardsContext';
import { FlashMessagesProvider } from '@/contexts/FlashMessagesContext';
import { CartContextProvider } from '@/contexts/CartContext';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cartify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <QueryProvider>
          <WizardsContextProvider>
            <FlashMessagesProvider>
              <AuthContextProvider>
                <CartContextProvider>{children}</CartContextProvider>
              </AuthContextProvider>
            </FlashMessagesProvider>
          </WizardsContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
