import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';
import './globals.css';
import MainLayout from '@/components/layout/MainLayout';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cartify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
