export interface IconProps {
  className?: string;
}

export { IconSelectArrows } from './IconSelectArrows';
export { IconLoupe } from './IconLoupe';
export { IconCart } from './IconCart';
export { IconUser } from './IconUser';
export { IconHeart } from './IconHeart';
export { IconTruck } from './IconTruck';
export { IconWallet } from './IconWallet';
export { IconHeadset } from './IconHeadset';
export { IconCard } from './IconCard';
export { IconStar } from './IconStar';
export { IconEye } from './IconEye';
export { IconPhone } from './IconPhone';
export { IconCamera } from './IconCamera';
export { IconTV } from './IconTV';
export { IconTop } from './IconTop';
export { IconGamepad } from './IconGamepad';
export { IconBasketball } from './IconBasketball';
export { IconChevronRight } from './IconChevronRight';
export { IconFacebook } from './IconFacebook';
export { IconTwitter } from './IconTwitter';
export { IconLinkedin } from './IconLinkedin';
export { IconInstagram } from './IconInstagram';
export { IconGithub } from './IconGithub';
export { IconGoogle } from './IconGoogle';
export { IconSuitcase } from './IconSuitcase';
export { IconTasks } from './IconTasks';
export { IconPrivacySettings } from './IconPrivacySettings';
export { IconMessages } from './IconMessages';
export { IconCalendar } from './IconCalendar';
export { IconUpload } from './IconUpload';
export { IconPlus } from './IconPlus';
export { IconX } from './IconX';
export { IconLocation } from './IconLocation';
export { IconSpeedometer } from './IconSpeedometer';
export { IconSales } from './IconSales';
export { IconWalletStroke } from './IconWalletStroke';
export { IconRate } from './IconRate';
